### ISSUE TITLE
better Metric names and base unit

### ISSUE THREAD

**Issue by ebini** [itzg/kube-metrics-exporter#1]
Hi,
i would appreciate to

a) have prometheus metric naming conventions and perhaps use the same convention than kube-state-metrics
https://prometheus.io/docs/practices/naming/
kube-state-metrics for example: kube_pod_container_resource_limits_cpu_cores
suggestion: 
container_cpu_usage => container_cpu_usage_cores 
and the values in cores and not millicores

for memory:

kube-state-metrics for example:  kube_pod_container_resource_requests_memory_bytes

suggestion: container_mem_usage => container_memory_usage_bytes 
and the value of memory in bytes 

Thanks

**Comment by itzg** [comment]
It's funny you mention kube-state-metrics since I recently discovered it does indeed satisfy my original use case. With that discovery, I was pondering archiving/deprecated this repo :) 

As a compromise, the suggested name changes you mentioned sound good. I'd be happy for a PR if you're up for it.

**Comment by ebini** [comment]
in kube-state-metrics i don't get the current usage. only the configuration. And i need a tool to get as unprivileged user (without clusterroles) cpu,memory usage.

 I'm not the great programmer, but i will give it a try ;-) => PR will need some time.

**Comment by itzg** [comment]
I'll be glad to make the changes -- I just wanted to put that option out there.

Meanwhile, I was thinking more that changing the metric names would break existing users of this image; however, I see there's only 12 pulls. So, now is the time to make this kind of "breaking" change.

**Comment by itzg** [comment]
...I started to make the code change, but I'm not sure yet how to go from a [Quantity](https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource@v0.17.0#Quantity) to a plain old float64 value that can be exported by Prometheus.

I took an easier path originally and scaled each to an integer value that was in the same units as `kubectl top`:
https://github.com/itzg/kube-metrics-exporter/blob/f40d9f2fea0ede1e7dd35724b0878fa77f5ec89e/pkg/collector.go#L54-L55

I'll have to research some more.

**Comment by ebini** [comment]
FYI: I asked a friend to take a look into this (good developer). He has probably time on Thursday
I assume he will create a PR or answer here.
